name: Deploy
description: Deploy artifact to a remote windows server
inputs:
  server:
    description: 'server ip'
    required: true
  account:
    description: 'server account'
    required: false
    default: 'Administrator'
  password:
    description: 'server password'
    required: true
  artifact:
    description: 'artifact path'
    required: false
    default: 'dist'
  path:
    description: 'deploy path'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
